---
#------
# db
#------
mw_db_user: "wikiuser"
mw_db_name: "wikidb"

#---------
# secrets
#--------
mw_db_password: "{{ vault_mw_db_password }}"
zbxdb_password: "{{ vault_zbxdb_password }}"
mediawiki_admin_pass: "{{ vault_mediawiki_admin_pass }}"
s3_key: "{{ vault_s3_key }}"
s3_secret: "{{ vault_s3_secret }}"
#---------
# zabbix-agent2 plugins
#---------
zxb_agent_plugins: 
  - zabbix-agent2-plugin-mongodb 
  - zabbix-agent2-plugin-mssql 
  - zabbix-agent2-plugin-postgresql 

external_ip: "111.88.248.177"
#-------
# bpotstrap
#-------
bootstrap_packages: 
  - wget
  - acl

