#SPDX-License-Identifier: MIT-0
---
# tasks file for  packages-wiki
- name: add ppa:ondrej/php
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "{{ wiki_packages }}"

