#SPDX-License-Identifier: MIT-0
---
# tasks file for mywiki
- name: download MediaWiki
  get_url:
    url: "{{ url }}"
    dest: /tmp/

- name: add php ppa repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: install php 8.2 and dependencies
  apt:
    name:
      - php8.2-cli
      - php8.2-pgsql
      - php8.2-xml
      - php8.2-mbstring
      - php8.2-intl
      - php8.2-gd
      - php8.2-curl
      - php8.2-fpm
    state: present
    update_cache: yes

- name: create directory for MediaWiki
  file:
    path: "{{ path_mywiki }}"
    state: directory
    owner: "www-data"


- name: find leader
  uri:
    url: "http://{{ hostvars[item]['ansible_host'] }}:8008/master"
    method: GET
    return_content: no
  register: patroni_results
  loop: "{{ groups['mwdb_postgresql_servers'] }}"
  failed_when: false
  become: false

- name: set leader_host
  set_fact:
    leader_host: "{{ hostvars[item.item]['ansible_host'] }}"
  loop: "{{ patroni_results.results }}"
  when: item.status == 200
  run_once: true

- name: check leader
  fail:
    msg: "ERROR master"
  when: leader_host is undefined
  run_once: true

- name: create MediaWiki database user
  community.postgresql.postgresql_user:
    name: "{{ mw_db_user }}"
    password: "{{ mw_db_password }}"
    encrypted: yes
    login_host: "{{ leader_host }}"
    login_user: postgres
    login_password: "{{ mw_db_password }}"
    state: present
  delegate_to: "{{ groups['mwdb_postgresql_servers'][0] }}"
  run_once: true
  become: false

- name: create MediaWiki database
  community.postgresql.postgresql_db:
    name: "{{ mw_db_name }}"
    owner: "{{ mw_db_user }}"
    login_host: "{{ leader_host }}"
    login_user: postgres
    login_password: "{{ mw_db_password }}"
    state: present
  delegate_to: "{{ groups['mwdb_postgresql_servers'][0] }}"
  run_once: true
  become: false

- name: Extract mediawiki.tar.gz into /var/www/mediawiki
  unarchive:
    src: /tmp/mediawiki-1.45.3.tar.gz
    dest: "{{ path_mywiki}}"
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: install MediaWiki
  shell: >
    php maintenance/install.php
    --dbtype="postgres" 
    --dbname="{{ mw_db_name }}" 
    --dbserver="{{ hostvars['haproxy-lb']['ansible_host'] }}" 
    --dbuser="{{ mw_db_user }}" 
    --dbpass="{{ mw_db_password}}"
    --dbmwschema="public" 
    --server="http://{{ external_ip }}" 
    --scriptpath=""
    --pass="{{ mediawiki_admin_pass }}" 
    "{{ mediawiki_name }}" "{{ mediawiki_admin_user }}"
  args:
    chdir: "{{ path_mywiki }}"
    creates: "{{ path_mywiki }}/LocalSettings.php"
  run_once: true
  notify: restart nginx

- name: fetch LocalSettings.php from mw-web1
  fetch:
    src: "{{ path_mywiki }}/LocalSettings.php"
    dest: "./LocalSettings.php"
    flat: yes
  run_once: true 

- name: copy LocalSettings.php to all web servers
  copy:
    src: "./LocalSettings.php"
    dest: "{{ path_mywiki }}/LocalSettings.php"
    owner: www-data
    group: www-data
    mode: '0644'
  notify: restart nginx
