---
- hosts: all
  gather_facts: yes

- hosts: zbx_servers
  roles:
    - bootstrap
    - zbx_server

- hosts: etcd_servers
  roles:
    - bootstrap
    - mwdb_etcd_cluster
    - zbx_agent2

- hosts: mwdb_postgresql_servers
  roles:
    - bootstrap
    - mwdb_postgresql
    - mwdb_patroni
    - zbx_agent2

- hosts: haproxy_servers
  roles:
    - bootstrap
    - lb_hapoxy
    - zbx_agent2

- hosts: web_servers
  roles:
    - bootstrap
    - web_packages
    - web_nginx
    - web_mediawiki
    - zbx_agent2

- hosts: lb_servers
  roles:
    - bootstrap
    - lb_nginx
    - zbx_agent2




    
