---
- hosts: etcd_servers
  roles:
    - bootstrap
    - mwdb_etcd_cluster

- hosts: mwdb_postgresql_servers
  roles:
    - bootstrap
    - mwdb_postgresql
    - mwdb_patroni

- hosts: haproxy_servers
  roles:
    - bootstrap
    - lb_hapoxy
