dev:
  children: 
    # --- WEB SERVERS ---
    web_servers: 
      hosts: 

    # --- MW_DB_MASTER SERVERS --- 
    mwdb_servers_master:
      hosts:

    # --- MW_DB_CLUSTERR SERVERS --- 
    mwdb_postgresql_servers:
      hosts:
        mw-postgresql-1:
          ansible_host: 10.10.10.19
        mw-postgresql-2:
          ansible_host: 10.10.10.10
        mw-postgresql-3:
          ansible_host: 10.10.10.21

    # --- MW_DB_REPLICA SERVERS --- 
    mwdb_servers_replica:
      hosts:

      # --- ETCD SERVERS ---
    etcd_servers:

    # --- LB SERVERS --- 
    lb_servers:
      hosts:
        lb-1:
          ansible_host: 111.88.254.127
          internal_ip:  10.10.10.27          
        lb-2:
          ansible_host: 89.169.159.53
          internal_ip:  10.10.10.9     



      # --- ZBX SERVERS ---
    zbx_servers:

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/yandex_key 
    connection_protocol: ssh
    ansible_become: true 