dev:
  children: 
    # --- WEB SERVERS ---
    web_servers: 
      hosts: 

    # --- MW_DB_MASTER SERVERS --- 
    mwdb_servers_master:
      hosts:

    # --- MW_DB_CLUSTERR SERVERS --- 
    mwdb_postgresql_servers:
      hosts:
        mw-postgresql-1:
          ansible_host: 10.10.10.14
        mw-postgresql-2:
          ansible_host: 10.10.10.32
        mw-postgresql-3:
          ansible_host: 10.10.10.25

    # --- MW_DB_REPLICA SERVERS --- 
    mwdb_servers_replica:
      hosts:

      # --- ETCD SERVERS ---
    etcd_servers:

    # --- LB SERVERS --- 
    lb_servers:
      hosts:
        lb-1:
          ansible_host: 89.169.134.220
          internal_ip:  10.10.10.29          
        lb-2:
          ansible_host: 111.88.247.85
          internal_ip:  10.10.10.11     
  
    # --- HAPROXY SERVERS ---
    haproxy_servers:
      hosts:
        haproxy-db:
          ansible_host: 10.10.10.17


      # --- ZBX SERVERS ---
    zbx_servers:

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/yandex_key 
    connection_protocol: ssh
    ansible_become: true 
