name: deploy-test
on:
  push: 
    branches: dev

env:
  AWS_ACCESS_KEY: "${{ secrets.YC_S3_ACCESS_KEY }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.YC_S3_SECRET_KEY }}"
  YC_CLOUD_ID: "${{ secrets.YC_CLOUD_ID }}"
  YC_FOLDER_ID: "${{ secrets.YC_FOLDER_ID }}"
  YC_SERVICE_ACCOUNT_KEY_FILE: "${{ github.workspace }}/.secrets/sa-key.json"
jobs:
  checl-my-runner:
    runs-on: self-hosted
    steps:
      - name: debug
        run: | 
          pwd
          ls -ld
          ls -la
      - name: Checkout code
        uses: actions/checkout@v6
      - name: secrets
        run: | 
          mkdir -p .secrets
          cat <<'EOF' > ${{ github.workspace }}/.secrets/sa-key.json
          ${{ secrets.YC_SA_JSON }}
          EOF
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ${{ github.workspace }}/.secrets/yandex_key.pub
          echo "${{ secrets.SSH_KEY }}" > ${{ github.workspace }}/.secrets/yandex_key
          chmod 600 ${{ github.workspace }}/.secrets/yandex_key
          chmod 644 ${{ github.workspace }}/.secrets/yandex_key.pub

      - name: terraform tfvars
        run: |
          cat <<'EOF'> dev/terraform/terraform.tfvars
          yandex_zone = "ru-central1-a"
          allowed_ports = [ "22", "3000", "3010" ]
          cidr_v4 = [ "10.10.10.0/24" ]
          vm_configuration = {
          "mw-web1" = { disk_name = "mw-disk1", disk_type = "network-ssd", vm_name = "mw-web1", vm_profile = "web" }
          "mw-web2" = { disk_name = "mw-disk2", disk_type = "network-ssd", vm_name = "mw-web2", vm_profile = "web" }
          "mw-postgresql-1" = { disk_name = "mw-psql-1", disk_type = "network-ssd", vm_name = "mw-psql-1", vm_profile = "db" }
          "mw-postgresql-2" = { disk_name = "mw-psql-2", disk_type = "network-ssd", vm_name = "mw-psql-2", vm_profile = "db" }
          "mw-postgresql-3" = { disk_name = "mw-psql-3", disk_type = "network-ssd", vm_name = "mw-psql-3", vm_profile = "db" }
          "haproxy-db" = { disk_name = "haproxy-db-disk", disk_type = "network-ssd", vm_name = "haproxy-db", vm_profile = "db" }
          "zbx-server1" = { disk_name = "zabbix-disk1", disk_type = "network-ssd", vm_name = "zbx-server1", vm_profile = "zbx" }
          }
          yc_region = "ru-central1-a"
          yc_balancer = { name = "yc-balancer", listener = "yc-balancer-1", listener_port = "80", healthcheck = "health-check-1", unhealthy = "3", healthy = "3", http_port = "80" }
          lb_group = {  name = "lb-nginx", folder_id = "${{ secrets.YC_FOLDER_ID }}", service_id = "ajetj0uq5io2kmnjjc0d", platform_id = "standard-v1", platform_id = "standard-v1", group_name = "yc-lb-1", fixed_scale   = 2 } 
          lb_group_profile = { cores = 2, ram = 2, disk_size = 10 }
          vm_user = "${{ secrets.SSH_USER }}"
          path_ssh = "${{ github.workspace }}/.secrets/yandex_key"
          private_path_ssh = "${{ github.workspace }}/.secrets/yandex_key"
          EOF

      - name: terraform init
        working-directory: dev/terraform
        run: |
          echo " --- DEBUG ---"
          echo "json file"
          head -c 50 "${{ github.workspace }}/.secrets/yandex_key"
          echo "file type"
          file "${{ github.workspace }}/.secrets/yandex_key"
          pwd
          ls -la "${{ github.workspace }}/.secrets/yandex_key"
          echo " --- DEBUG ---"
          terraform init

      - name: terraform plan
        working-directory: dev/terraform
        run: terraform plan

      - name: terraform destroy
        working-directory: dev/terraform
        run: terraform destroy -auto-approve

